baseURL = "https://www.aureldvx.fr"
languageCode = "fr-fr"
title = "Aurélien Devaux ~ Portfolio"
theme = "aureldvx-theme"
canonifyURLs = true
enableEmoji = true
pygmentsCodefences = true
pygmentsStyle = "dracula"

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
	[markup.highlight]
	  codeFences = true
	  guessSyntax = false
	  hl_Lines = ""
	  lineNoStart = 1
	  lineNos = true
	  lineNumbersInTable = true
	  noClasses = true
	  style = "dracula"
	  tabWidth = 2

[menu]

  [[menu.main]]
    identifier = "projects"
		name = "Projets."
    url = "/projects/"
    weight = 1

	[[menu.main]]
    identifier = "about"
    name = "Expériences."
    url = "/about/"
    weight = 2

	[[menu.main]]
    identifier = "skills"
		name = "Compétences."
    url = "/skills/"
    weight = 3